--- block/Makefile
+++ block/Makefile
@@ -17,6 +17,13 @@ obj-$(CONFIG_IOSCHED_DEADLINE)	+= deadline-iosched.o
 obj-$(CONFIG_IOSCHED_ROW)	+= row-iosched.o
 obj-$(CONFIG_IOSCHED_CFQ)	+= cfq-iosched.o
 obj-$(CONFIG_IOSCHED_TEST)	+= test-iosched.o
+obj-$(CONFIG_IOSCHED_SIO)   	+= sio-iosched.o
+obj-$(CONFIG_IOSCHED_FIFO)   	+= fifo-iosched.o
+obj-$(CONFIG_IOSCHED_FIOPS)     += fiops-iosched.o
+obj-$(CONFIG_IOSCHED_BFQ)        += bfq-iosched.o
+obj-$(CONFIG_IOSCHED_ZEN)        += zen-iosched.o
+obj-$(CONFIG_IOSCHED_VR)        += vr-iosched.o
+obj-$(CONFIG_IOSCHED_SIOPLUS)        += sioplus-iosched.o
 
 obj-$(CONFIG_BLOCK_COMPAT)	+= compat_ioctl.o
 obj-$(CONFIG_BLK_DEV_INTEGRITY)	+= blk-integrity.o
